// Common grocery searches, for suggestions before the phone has read anything: each item and the kinds people ask
// for by name ("whole milk", "oat milk"). Lower case, as typed. Brands appear where shoppers search by them.

const GROUPS: Record<string, string[]> = {
  dairy: [
    'milk', 'whole milk', '2% milk', '1% milk', 'skim milk', 'fat free milk', 'lactose free milk', 'organic milk',
    'chocolate milk', 'buttermilk', 'oat milk', 'almond milk', 'soy milk', 'coconut milk', 'half and half',
    'heavy cream', 'heavy whipping cream', 'whipped cream', 'coffee creamer', 'sour cream', 'cream cheese',
    'butter', 'salted butter', 'unsalted butter', 'margarine', 'eggs', 'large eggs', 'extra large eggs',
    'cage free eggs', 'organic eggs', 'egg whites', 'yogurt', 'greek yogurt', 'vanilla yogurt', 'plain yogurt',
    'strawberry yogurt', 'kids yogurt', 'drinkable yogurt', 'cottage cheese', 'cheese', 'cheddar cheese',
    'sharp cheddar', 'shredded cheese', 'shredded mozzarella', 'mozzarella', 'fresh mozzarella', 'parmesan',
    'grated parmesan', 'swiss cheese', 'american cheese', 'provolone', 'pepper jack', 'colby jack', 'string cheese',
    'feta', 'goat cheese', 'ricotta', 'brie', 'sliced cheese', 'cheese sticks',
  ],
  produce: [
    'bananas', 'apples', 'gala apples', 'honeycrisp apples', 'granny smith apples', 'fuji apples', 'oranges',
    'navel oranges', 'mandarins', 'clementines', 'lemons', 'limes', 'grapefruit', 'grapes', 'red grapes',
    'green grapes', 'strawberries', 'blueberries', 'raspberries', 'blackberries', 'cherries', 'watermelon',
    'cantaloupe', 'honeydew', 'pineapple', 'mango', 'peaches', 'nectarines', 'plums', 'pears', 'kiwi', 'avocados',
    'tomatoes', 'roma tomatoes', 'cherry tomatoes', 'grape tomatoes', 'potatoes', 'russet potatoes',
    'red potatoes', 'yukon gold potatoes', 'sweet potatoes', 'onions', 'yellow onions', 'red onions',
    'white onions', 'green onions', 'shallots', 'garlic', 'ginger', 'carrots', 'baby carrots', 'celery',
    'broccoli', 'broccoli florets', 'cauliflower', 'spinach', 'baby spinach', 'kale', 'lettuce', 'romaine lettuce',
    'iceberg lettuce', 'spring mix', 'salad kit', 'cabbage', 'brussels sprouts', 'asparagus', 'green beans',
    'zucchini', 'yellow squash', 'butternut squash', 'cucumbers', 'bell peppers', 'red bell peppers',
    'green bell peppers', 'jalapenos', 'mushrooms', 'baby bella mushrooms', 'corn on the cob', 'eggplant',
    'cilantro', 'parsley', 'basil', 'mint', 'rosemary', 'fresh herbs',
  ],
  meat: [
    'chicken', 'chicken breast', 'boneless chicken breast', 'chicken thighs', 'boneless chicken thighs',
    'chicken wings', 'chicken drumsticks', 'whole chicken', 'rotisserie chicken', 'chicken tenders',
    'ground beef', '80/20 ground beef', '90/10 ground beef', 'lean ground beef', 'ground turkey', 'ground chicken',
    'ground pork', 'steak', 'ribeye steak', 'sirloin steak', 'new york strip', 'flank steak', 'chuck roast',
    'stew meat', 'beef brisket', 'pork chops', 'pork tenderloin', 'pork shoulder', 'ribs', 'baby back ribs',
    'bacon', 'thick cut bacon', 'turkey bacon', 'breakfast sausage', 'italian sausage', 'sausage links',
    'bratwurst', 'hot dogs', 'beef hot dogs', 'ham', 'sliced ham', 'deli turkey', 'deli ham', 'lunch meat',
    'salami', 'pepperoni', 'prosciutto', 'meatballs', 'turkey breast', 'lamb chops',
  ],
  seafood: [
    'salmon', 'salmon fillets', 'shrimp', 'frozen shrimp', 'cooked shrimp', 'tilapia', 'cod', 'tuna steaks',
    'crab legs', 'lobster tails', 'scallops', 'fish sticks', 'canned tuna', 'canned salmon', 'sardines',
  ],
  bakery: [
    'bread', 'white bread', 'wheat bread', 'whole wheat bread', 'sourdough bread', 'rye bread', 'multigrain bread',
    'bagels', 'english muffins', 'hot dog buns', 'hamburger buns', 'dinner rolls', 'hawaiian rolls', 'tortillas',
    'flour tortillas', 'corn tortillas', 'pita bread', 'naan', 'croissants', 'muffins', 'donuts', 'cake',
    'cupcakes', 'cookies', 'pie', 'brioche buns', 'french bread', 'garlic bread',
  ],
  pantry: [
    'rice', 'white rice', 'brown rice', 'jasmine rice', 'basmati rice', 'instant rice', 'pasta', 'spaghetti',
    'penne', 'elbow macaroni', 'rotini', 'lasagna noodles', 'egg noodles', 'ramen', 'mac and cheese',
    'pasta sauce', 'marinara sauce', 'alfredo sauce', 'pesto', 'tomato sauce', 'tomato paste', 'diced tomatoes',
    'crushed tomatoes', 'canned tomatoes', 'black beans', 'pinto beans', 'kidney beans', 'chickpeas',
    'refried beans', 'baked beans', 'lentils', 'canned corn', 'canned green beans', 'chicken broth', 'beef broth',
    'vegetable broth', 'soup', 'chicken noodle soup', 'tomato soup', 'cream of mushroom soup', 'chili',
    'flour', 'all purpose flour', 'bread flour', 'sugar', 'brown sugar', 'powdered sugar', 'baking soda',
    'baking powder', 'yeast', 'vanilla extract', 'chocolate chips', 'cocoa powder', 'cornstarch', 'cake mix',
    'brownie mix', 'pancake mix', 'maple syrup', 'pancake syrup', 'honey', 'peanut butter', 'creamy peanut butter',
    'crunchy peanut butter', 'almond butter', 'jelly', 'grape jelly', 'strawberry jam', 'nutella', 'oatmeal',
    'rolled oats', 'instant oatmeal', 'cereal', 'granola', 'cheerios', 'honey nut cheerios', 'frosted flakes',
    'corn flakes', 'raisin bran', 'special k', 'froot loops', 'lucky charms', 'cinnamon toast crunch',
    'olive oil', 'extra virgin olive oil', 'vegetable oil', 'canola oil', 'coconut oil', 'avocado oil',
    'cooking spray', 'vinegar', 'apple cider vinegar', 'balsamic vinegar', 'salt', 'sea salt', 'kosher salt',
    'black pepper', 'garlic powder', 'onion powder', 'paprika', 'cinnamon', 'cumin', 'chili powder',
    'italian seasoning', 'taco seasoning', 'bread crumbs', 'croutons', 'stuffing mix',
  ],
  condiments: [
    'ketchup', 'heinz ketchup', 'mustard', 'yellow mustard', 'dijon mustard', 'mayonnaise', 'hellmanns mayonnaise',
    'miracle whip', 'relish', 'bbq sauce', 'hot sauce', 'sriracha', 'soy sauce', 'teriyaki sauce',
    'worcestershire sauce', 'ranch dressing', 'italian dressing', 'caesar dressing', 'salad dressing', 'salsa',
    'queso', 'guacamole', 'hummus', 'pickles', 'dill pickles', 'olives', 'capers', 'syrup', 'steak sauce',
  ],
  frozen: [
    'frozen pizza', 'frozen vegetables', 'frozen broccoli', 'frozen corn', 'frozen peas', 'frozen mixed vegetables',
    'frozen fruit', 'frozen berries', 'frozen strawberries', 'frozen blueberries', 'frozen french fries',
    'tater tots', 'hash browns', 'frozen waffles', 'frozen pancakes', 'frozen burritos', 'frozen dinners',
    'frozen chicken nuggets', 'chicken nuggets', 'fish fillets', 'ice cream', 'vanilla ice cream',
    'chocolate ice cream', 'ice cream sandwiches', 'popsicles', 'frozen yogurt', 'pie crust', 'frozen meatballs',
    'pizza rolls', 'egg rolls', 'dumplings', 'frozen lasagna',
  ],
  snacks: [
    'chips', 'potato chips', 'tortilla chips', 'doritos', 'lays', 'pringles', 'cheetos', 'pretzels', 'popcorn',
    'microwave popcorn', 'crackers', 'goldfish crackers', 'ritz crackers', 'cheez-its', 'graham crackers',
    'saltine crackers', 'rice cakes', 'granola bars', 'protein bars', 'trail mix', 'nuts', 'almonds', 'cashews',
    'peanuts', 'pistachios', 'walnuts', 'pecans', 'mixed nuts', 'sunflower seeds', 'beef jerky', 'fruit snacks',
    'applesauce', 'fruit cups', 'pudding', 'jello', 'oreos', 'chocolate', 'candy', 'gummy bears', 'gum',
  ],
  drinks: [
    'water', 'bottled water', 'sparkling water', 'seltzer', 'coconut water', 'orange juice', 'apple juice',
    'grape juice', 'cranberry juice', 'lemonade', 'juice boxes', 'soda', 'coca-cola', 'diet coke', 'coke zero',
    'pepsi', 'sprite', 'ginger ale', 'root beer', 'dr pepper', 'mountain dew', 'iced tea', 'sweet tea',
    'green tea', 'tea bags', 'coffee', 'ground coffee', 'whole bean coffee', 'k-cups', 'coffee pods',
    'instant coffee', 'cold brew', 'energy drinks', 'red bull', 'sports drinks', 'gatorade', 'kombucha',
    'hot chocolate', 'beer', 'wine', 'red wine', 'white wine', 'seltzer water',
  ],
  household: [
    'paper towels', 'bounty paper towels', 'toilet paper', 'charmin toilet paper', 'napkins', 'paper plates',
    'plastic cups', 'plastic forks', 'tissues', 'kleenex', 'trash bags', 'kitchen trash bags', 'ziploc bags',
    'sandwich bags', 'freezer bags', 'aluminum foil', 'plastic wrap', 'parchment paper', 'dish soap',
    'dishwasher detergent', 'dishwasher pods', 'laundry detergent', 'tide pods', 'laundry pods', 'fabric softener',
    'dryer sheets', 'bleach', 'all purpose cleaner', 'disinfecting wipes', 'clorox wipes', 'glass cleaner',
    'sponges', 'light bulbs', 'batteries', 'aa batteries', 'air freshener', 'candles', 'matches', 'charcoal',
  ],
  'personal care': [
    'shampoo', 'conditioner', 'body wash', 'bar soap', 'hand soap', 'toothpaste', 'toothbrush', 'mouthwash',
    'dental floss', 'deodorant', 'razors', 'shaving cream', 'lotion', 'sunscreen', 'lip balm', 'cotton balls',
    'q-tips', 'band-aids', 'pain reliever', 'ibuprofen', 'acetaminophen', 'vitamins', 'allergy medicine',
    'cough drops', 'feminine products', 'tampons', 'pads',
  ],
  baby: ['diapers', 'baby wipes', 'baby formula', 'baby food', 'pull-ups', 'baby shampoo'],
  pets: ['dog food', 'dry dog food', 'wet dog food', 'dog treats', 'cat food', 'dry cat food', 'wet cat food', 'cat litter', 'cat treats'],
};

/** Every term, once, in the order above: the most common kinds of each item first. */
export const GROCERY_TERMS: string[] = [...new Set(Object.values(GROUPS).flat())];
